name: CI/CD Pipeline for Car CRUD App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VERSION: '1.5.0'

jobs:
  # Phase 3: Build
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Build the application (if necessary)
        run: |
          echo "No specific build process defined."

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: car-crud-app-dist
          path: .

  # Phase 4: Test
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: car-crud-app-dist
          path: .

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest -s tests/test_unitary.py

      - name: Run Integration Tests
        run: |
          python -m unittest discover -s tests -p "test_integration.py"

      - name: Run Functionality Tests
        run: |
          python -m unittest tests.test_functionality

      - name: Start the application for performance tests
        run: |
          python app.py &
          echo $! > app_pid.txt  # Guarda el PID del proceso para detenerlo más tarde

      - name: Wait for the application to be ready
        run: |
          for i in {1..30}; do
            curl -s http://localhost:5000 && break
            sleep 1
          done

      - name: Run Performance Tests
        run: |
          locust -f tests/test_performance.py --host=http://localhost:5000

      - name: Stop the application
        if: always()
        run: |
          kill $(cat app_pid.txt) || true

      - name: Run Quality Tests
        run: |
          pylint app.py

      - name: Install Trivy for Security Tests
        run: |
          sudo apt-get install -y wget && \
          wget https://github.com/aquasecurity/trivy/releases/download/v0.46.0/trivy_0.46.0_Linux-64bit.deb && \
          sudo dpkg -i trivy_0.46.0_Linux-64bit.deb

      - name: Run Security Tests
        run: |
          ./tests/test_security.sh

  # Phase 5: Release
  release:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Git Tag for Release
        run: |
          TAG="release-$(date +'%Y%m%d-%H%M%S')"
          git tag $TAG
          git push origin $TAG

  # Phase 6: Infrastructure Setup (Terraform)
  infrastructure:
    needs: release
    runs-on: ubuntu-latest
    outputs:
      website_bucket: ${{ steps.terraform-outputs.outputs.website_bucket }}
      artifacts_bucket: ${{ steps.terraform-outputs.outputs.artifacts_bucket }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: ./iac
        run: terraform init

      - name: Terraform Plan
        working-directory: ./iac
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./iac
        run: terraform apply -auto-approve tfplan

      - name: Get Terraform Outputs
        working-directory: ./iac
        id: terraform-outputs
        run: |
          terraform output -raw website_bucket_name > website_bucket.txt
          terraform output -raw artifacts_bucket_name > artifacts_bucket.txt
          echo "website_bucket=$(cat website_bucket.txt)" >> "$GITHUB_OUTPUT"
          echo "artifacts_bucket=$(cat artifacts_bucket.txt)" >> "$GITHUB_OUTPUT"

  # Phase 7: Deploy to Cloud
  deploy:
    needs: infrastructure
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: car-crud-app-dist
          path: dist

      - name: Deploy site to S3
        env:
          WEBSITE_BUCKET: ${{ needs.infrastructure.outputs.website_bucket }}
        run: |
          aws s3 sync dist/ "s3://$WEBSITE_BUCKET/"

      - name: Copy artifact to S3
        env:
          ARTIFACTS_BUCKET: ${{ needs.infrastructure.outputs.artifacts_bucket }}
        run: |
          cd dist && zip -r ../car-crud-app.zip .
          aws s3 cp car-crud-app.zip "s3://${ARTIFACTS_BUCKET}/car-crud-app.zip"

  # Phase 8: Monitor
  monitor:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Install Grafana
        run: |
          curl -LO https://dl.grafana.com/oss/release/grafana_9.5.3_amd64.deb
          sudo dpkg -i grafana_9.5.3_amd64.deb
          sudo systemctl start grafana-server
          sudo systemctl enable grafana-server

      - name: Install Prometheus
        run: |
          curl -LO https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
          tar -xvf prometheus-2.43.0.linux-amd64.tar.gz
          sudo mv prometheus-2.43.0.linux-amd64/prometheus /usr/local/bin/
          sudo mv prometheus-2.43.0.linux-amd64/promtool /usr/local/bin/
          sudo systemctl start prometheus
          sudo systemctl enable prometheus
